// src/modules/state.js
export const state = {
    activeDept: 'bible',
    user: null,
    settings: {
        theme: 'dark',
        fontFamily: "'Inter', sans-serif",
        fontSize: 48,
        primaryColor: '#007bff'
    },
    formatting: {
        fontFamily: "'Inter', sans-serif",
        fontSize: 48,
        color: '#ffffff',
        outlineColor: '#000000',
        outlineThickness: 0,
        shadowColor: '#000000',
        shadowAngle: 45,
        shadowDistance: 5,
        shadowBlur: 5,
        shadowThickness: 0,
        glowColor: '#007bff',
        glowThickness: 0,
        bgType: 'color',
        bgColor: '#000000',
        bgFile: null,
        entryType: 'none',
        entryDuration: 500,
        exitType: 'none',
        exitDuration: 500,
        posX: 50,
        posY: 50
    },
    media: {
        assets: [],
        activeAsset: null,
        isPaused: true,
        loop: false,
        isOverlay: false,
        volume: 100
    },
    presentation: {
        timerId: null,
        remainingTime: 0,
        isPaused: false,
        currentText: '',
        lastTimestamp: 0
    },
    history: {
        bible: [],
        media: [],
        songs: [],
        timers: []
    },
    bible: {
        selectedBook: null,
        selectedChapter: null,
        selectedVerses: [], // Array of verse numbers
        isDragging: false,
        hasMoved: false,
        dragStartVerse: null,
        books: [
            { name: 'Genesis', code: 'GEN', chapters: 50, genre: 'ot-law' },
            { name: 'Exodus', code: 'EXO', chapters: 40, genre: 'ot-law' },
            { name: 'Leviticus', code: 'LEV', chapters: 27, genre: 'ot-law' },
            { name: 'Numbers', code: 'NUM', chapters: 36, genre: 'ot-law' },
            { name: 'Deuteronomy', code: 'DEU', chapters: 34, genre: 'ot-law' },
            { name: 'Joshua', code: 'JOS', chapters: 24, genre: 'ot-history' },
            { name: 'Judges', code: 'JDG', chapters: 21, genre: 'ot-history' },
            { name: 'Ruth', code: 'RUT', chapters: 4, genre: 'ot-history' },
            { name: '1 Samuel', code: '1SAM', chapters: 31, genre: 'ot-history' },
            { name: '2 Samuel', code: '2SAM', chapters: 24, genre: 'ot-history' },
            { name: '1 Kings', code: '1KI', chapters: 22, genre: 'ot-history' },
            { name: '2 Kings', code: '2KI', chapters: 25, genre: 'ot-history' },
            { name: '1 Chronicles', code: '1CH', chapters: 29, genre: 'ot-history' },
            { name: '2 Chronicles', code: '2CH', chapters: 36, genre: 'ot-history' },
            { name: 'Ezra', code: 'EZR', chapters: 10, genre: 'ot-history' },
            { name: 'Nehemiah', code: 'NEH', chapters: 13, genre: 'ot-history' },
            { name: 'Esther', code: 'EST', chapters: 10, genre: 'ot-history' },
            { name: 'Job', code: 'JOB', chapters: 42, genre: 'ot-poetry' },
            { name: 'Psalms', code: 'PSA', chapters: 150, genre: 'ot-poetry' },
            { name: 'Proverbs', code: 'PRO', chapters: 31, genre: 'ot-poetry' },
            { name: 'Ecclesiastes', code: 'ECC', chapters: 12, genre: 'ot-poetry' },
            { name: 'Song of Solomon', code: 'SONG', chapters: 8, genre: 'ot-poetry' },
            { name: 'Isaiah', code: 'ISA', chapters: 66, genre: 'ot-major' },
            { name: 'Jeremiah', code: 'JER', chapters: 52, genre: 'ot-major' },
            { name: 'Lamentations', code: 'LAM', chapters: 5, genre: 'ot-major' },
            { name: 'Ezekiel', code: 'EZE', chapters: 48, genre: 'ot-major' },
            { name: 'Daniel', code: 'DAN', chapters: 12, genre: 'ot-major' },
            { name: 'Hosea', code: 'HOS', chapters: 14, genre: 'ot-minor' },
            { name: 'Joel', code: 'JOE', chapters: 3, genre: 'ot-minor' },
            { name: 'Amos', code: 'AMO', chapters: 9, genre: 'ot-minor' },
            { name: 'Obadiah', code: 'OBA', chapters: 1, genre: 'ot-minor' },
            { name: 'Jonah', code: 'JON', chapters: 4, genre: 'ot-minor' },
            { name: 'Micah', code: 'MIC', chapters: 7, genre: 'ot-minor' },
            { name: 'Nahum', code: 'NAH', chapters: 3, genre: 'ot-minor' },
            { name: 'Habakkuk', code: 'HAB', chapters: 3, genre: 'ot-minor' },
            { name: 'Zephaniah', code: 'ZEP', chapters: 3, genre: 'ot-minor' },
            { name: 'Haggai', code: 'HAG', chapters: 2, genre: 'ot-minor' },
            { name: 'Zechariah', code: 'ZEC', chapters: 14, genre: 'ot-minor' },
            { name: 'Malachi', code: 'MAL', chapters: 4, genre: 'ot-minor' },
            { name: 'Matthew', code: 'MAT', chapters: 28, genre: 'nt-gospel' },
            { name: 'Mark', code: 'MAR', chapters: 16, genre: 'nt-gospel' },
            { name: 'Luke', code: 'LUK', chapters: 24, genre: 'nt-gospel' },
            { name: 'John', code: 'JOH', chapters: 21, genre: 'nt-gospel' },
            { name: 'Acts', code: 'ACT', chapters: 28, genre: 'nt-history' },
            { name: 'Romans', code: 'ROM', chapters: 16, genre: 'nt-pauline' },
            { name: '1 Corinthians', code: '1COR', chapters: 16, genre: 'nt-pauline' },
            { name: '2 Corinthians', code: '2COR', chapters: 13, genre: 'nt-pauline' },
            { name: 'Galatians', code: 'GAL', chapters: 6, genre: 'nt-pauline' },
            { name: 'Ephesians', code: 'EPH', chapters: 6, genre: 'nt-pauline' },
            { name: 'Philippians', code: 'PHI', chapters: 4, genre: 'nt-pauline' },
            { name: 'Colossians', code: 'COL', chapters: 4, genre: 'nt-pauline' },
            { name: '1 Thessalonians', code: '1TH', chapters: 5, genre: 'nt-pauline' },
            { name: '2 Thessalonians', code: '2TH', chapters: 3, genre: 'nt-pauline' },
            { name: '1 Timothy', code: '1TI', chapters: 6, genre: 'nt-pauline' },
            { name: '2 Timothy', code: '2TI', chapters: 4, genre: 'nt-pauline' },
            { name: 'Titus', code: 'TIT', chapters: 3, genre: 'nt-pauline' },
            { name: 'Philemon', code: 'PHM', chapters: 1, genre: 'nt-pauline' },
            { name: 'Hebrews', code: 'HEB', chapters: 13, genre: 'nt-general' },
            { name: 'James', code: 'JAM', chapters: 5, genre: 'nt-general' },
            { name: '1 Peter', code: '1PE', chapters: 5, genre: 'nt-general' },
            { name: '2 Peter', code: '2PE', chapters: 3, genre: 'nt-general' },
            { name: '1 John', code: '1JO', chapters: 5, genre: 'nt-general' },
            { name: '2 John', code: '2JO', chapters: 1, genre: 'nt-general' },
            { name: '3 John', code: '3JO', chapters: 1, genre: 'nt-general' },
            { name: 'Jude', code: 'JUD', chapters: 1, genre: 'nt-general' },
            { name: 'Revelation', code: 'REV', chapters: 22, genre: 'nt-revelation' }
        ]
    }
};
